"""test models

Revision ID: 1063ebfc96bf
Revises: e8f9d6c204f0
Create Date: 2023-02-22 11:30:10.729365

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1063ebfc96bf'
down_revision = 'e8f9d6c204f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('day', 'weekday',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('day', 'week_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('task', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('task', 'deadline',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('task', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('task', 'day_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('week', 'start_day',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index('ix_week_owner_id', table_name='week')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_week_owner_id', 'week', ['owner_id'], unique=False)
    op.alter_column('week', 'start_day',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('task', 'day_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('task', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('task', 'deadline',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('day', 'week_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('day', 'weekday',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###
