"""verification_ids_table

Revision ID: 1cb448911678
Revises: daff311cf7d5
Create Date: 2023-03-28 23:07:04.948768

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1cb448911678"
down_revision = "daff311cf7d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_ids",
        sa.Column("verification_id", sa.UUID(), nullable=True),
        sa.Column("valid_until", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("verification_ids")
    # ### end Alembic commands ###
