"""code field type changed

Revision ID: 326e39a34c27
Revises: 4220c039ea94
Create Date: 2023-03-30 14:21:07.856121

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "326e39a34c27"
down_revision = "4220c039ea94"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "verification_ids", "verification_code", existing_type=sa.UUID(), nullable=False, type_=sa.String(length=40)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("verification_ids", "verification_code", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
