"""optional description

Revision ID: 4348dfe1af58
Revises: 1063ebfc96bf
Create Date: 2023-02-22 11:31:24.016006

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4348dfe1af58"
down_revision = "1063ebfc96bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("task", "description", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("task", "description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
