"""new relations

Revision ID: 46df3b8662c3
Revises: 4348dfe1af58
Create Date: 2023-02-22 16:02:31.971299

"""

# revision identifiers, used by Alembic.
revision = '46df3b8662c3'
down_revision = '4348dfe1af58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
