"""Update relationships

Revision ID: 4c65502a0302
Revises: 
Create Date: 2022-12-25 10:54:39.772867

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4c65502a0302"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=60), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "task",
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=60), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_owner_id"), ["owner_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_owner_id"))

    op.drop_table("task")
    op.drop_table("user")
    # ### end Alembic commands ###
