"""empty message

Revision ID: 640539169725
Revises: 
Create Date: 2023-02-20 23:01:39.856336

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "640539169725"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=60), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "week",
        sa.Column("start_day", sa.Date(), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_index(op.f("ix_week_owner_id"), "week", ["owner_id"], unique=False)
    op.create_table(
        "day",
        sa.Column("weekday", sa.String(length=15), nullable=True),
        sa.Column("week_id", sa.BigInteger(), nullable=True),
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["week_id"],
            ["week.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "task",
        sa.Column("title", sa.String(length=60), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("day_id", sa.BigInteger(), nullable=True),
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["day.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    op.drop_table("day")
    op.drop_index(op.f("ix_week_owner_id"), table_name="week")
    op.drop_table("week")
    op.drop_table("user")
    # ### end Alembic commands ###
