"""Added first table

Revision ID: cae5d111eed7
Revises: e902b8d25186
Create Date: 2022-12-23 13:19:04.219234

"""

# revision identifiers, used by Alembic.
revision = 'cae5d111eed7'
down_revision = 'e902b8d25186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
