"""Create table tasks

Revision ID: e902b8d25186
Revises: 
Create Date: 2022-12-15 11:55:27.702131

"""

# revision identifiers, used by Alembic.
revision = "e902b8d25186"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
